# Generated by Django 5.2.5 on 2025-08-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="введите ваш chat_id",
                max_length=100,
                unique=True,
                verbose_name="chat_id",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True,
                help_text="введите ваш tg_id",
                max_length=100,
                unique=True,
                verbose_name="tg_id",
            ),
        ),
    ]
