# Generated by Django 5.2.5 on 2025-08-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="linked_habit",
            new_name="link_habit",
        ),
    ]
